---
- fail:
    msg: |
      This module no longer maintain.
      @see https://github.com/yukihiko-shinoda/ansible-role-host-name-amazon-linux
      @see https://github.com/yukihiko-shinoda/ansible-role-ssl-certificate-amazon-linux
